import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';

const output=`output/browser-review-${Date.now()}`;await fs.mkdir(output,{recursive:true});
const server=spawn(process.env.PYTHON||'python',['-u','scripts/app_server.py','--port','8876'],{windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser;
try{
  const base=await new Promise((resolve,reject)=>{
    const timeout=setTimeout(()=>reject(Error('Local review server did not start')),15000);
    let text='';server.stdout.on('data',chunk=>{text+=chunk;const match=text.match(/Local app running at (http:\/\/[^\s]+)/);if(match){clearTimeout(timeout);resolve(match[1]);}});
    server.on('error',error=>{clearTimeout(timeout);reject(error);});server.on('exit',code=>{clearTimeout(timeout);reject(Error(`Server exited ${code}`));});
  });
  browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
  const input=JSON.parse(await fs.readFile('examples/commuter-mug-input.json','utf8'));
  const proposals=JSON.parse(await fs.readFile('examples/commuter-mug-decisions.json','utf8'));
  const file=value=>({name:'hypotheses.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});
  const reports=[];
  for(const width of [1440,390]){
    const context=await browser.newContext({viewport:{width,height:1000},acceptDownloads:true});
    const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto(base);
    await page.getByRole('button',{name:'Load sample',exact:true}).click();
    await page.locator('#status').filter({hasText:'Fictional sample loaded'}).waitFor();
    await page.getByRole('button',{name:'Analyze observations',exact:true}).click();
    await page.locator('#status').filter({hasText:'Review ready'}).waitFor();
    await page.getByRole('button',{name:'Hypotheses',exact:true}).click();
    await page.getByRole('button',{name:'Try sample hypotheses',exact:true}).click();
    await page.locator('.hypothesis').waitFor();assert.equal(await page.locator('.hypothesis').count(),1);
    // A second category has two independently reviewable hypotheses.
    await page.locator('#brief').fill(input.brief);await page.locator('#competitors').fill(input.competitors_csv);
    await page.getByRole('button',{name:'Analyze observations',exact:true}).click();await page.locator('#status').filter({hasText:'Review ready'}).waitFor();
    await page.getByRole('button',{name:'Hypotheses',exact:true}).click();
    await page.locator('#hypothesis-file').setInputFiles(file(proposals));
    await page.locator('#status').filter({hasText:'Citations checked'}).waitFor();
    assert.equal(await page.locator('.hypothesis').count(),2);
    await page.locator('#hypothesis-file').setInputFiles(file(null));
    await page.locator('#status').filter({hasText:'Import a hypothesis or review JSON object'}).waitFor();
    assert.equal(await page.locator('.hypothesis').count(),2);
    const first=page.locator('#hypothesis-P001');
    await first.locator('select').selectOption('test');await first.getByRole('button',{name:'Record choice'}).click();
    assert.equal(await first.locator('.recorded-choice').textContent(),'Recorded: Not reviewed');
    await first.locator('textarea').fill('   ');await first.getByRole('button',{name:'Record choice'}).click();
    await first.locator('select').selectOption('unreviewed');await first.getByRole('button',{name:'Record choice'}).click();
    assert.equal(await first.locator('textarea').inputValue(),'');
    await first.locator('select').selectOption('test');
    await first.locator('textarea').fill('Fictional review: 核对反例 before testing 🧪');
    await page.getByRole('button',{name:'Evidence',exact:true}).click();await page.getByRole('button',{name:'Hypotheses',exact:true}).click();
    assert.equal(await first.locator('textarea').inputValue(),'Fictional review: 核对反例 before testing 🧪');
    await first.getByRole('button',{name:'Record choice'}).click();
    assert.equal(await first.locator('.recorded-choice').textContent(),'Recorded: Plan a test');
    await page.getByRole('button',{name:'Undo last choice'}).click();assert.equal(await first.locator('select').inputValue(),'unreviewed');
    await first.locator('select').selectOption('reject');await first.locator('textarea').fill('Fictional review: evidence is not sufficient for this test.');await first.getByRole('button',{name:'Record choice'}).click();
    const cited=first.locator('details').nth(1);await cited.locator('summary').click();await cited.getByRole('button').first().click();
    assert(await cited.locator('.citation-original').first().isVisible());
    assert((await cited.locator('.source-original').first().textContent()).includes(proposals.proposals[0].evidence[0].quote));
    const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download review',exact:true}).click();
    const download=await downloadPromise;const target=`${output}/review-${width}.json`;await download.saveAs(target);
    const saved=JSON.parse(await fs.readFile(target,'utf8'));
    assert.deepEqual(saved.summary.choices,{unreviewed:1,test:0,defer:0,reject:1});
    assert.equal(saved.summary.reviewed_count,1);assert.equal(saved.summary.validation_status,'not_measured');
    assert.deepEqual(saved.decisions,proposals);
    const notesPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download review notes',exact:true}).click();
    const notes=await notesPromise;await notes.saveAs(`${output}/notes-${width}.md`);
    assert((await fs.readFile(`${output}/notes-${width}.md`,'utf8')).includes(saved.review.entries[0].reason));
    const changed=structuredClone(saved);changed.decisions.proposals[0].proposed_change='Changed fictional test';
    await page.locator('#hypothesis-file').setInputFiles(file(changed));await page.locator('#status').filter({hasText:'Hypotheses changed'}).waitFor();
    assert.equal(await first.locator('.recorded-choice').textContent(),'Recorded: Reject');
    const falseQuote=structuredClone(proposals);falseQuote.proposals[0].evidence[0].quote='Invented independent proof';
    await page.locator('#hypothesis-file').setInputFiles(file(falseQuote));await page.locator('#status').filter({hasText:'quoted text'}).waitFor();
    assert.equal(await first.locator('.recorded-choice').textContent(),'Recorded: Reject');
    await page.reload();await page.locator('#brief').fill(input.brief);await page.locator('#competitors').fill(input.competitors_csv);
    await page.getByRole('button',{name:'Analyze observations',exact:true}).click();await page.locator('#status').filter({hasText:'Review ready'}).waitFor();
    await page.getByRole('button',{name:'Hypotheses',exact:true}).click();await page.locator('#hypothesis-file').setInputFiles(file(saved));
    await page.locator('#status').filter({hasText:'Review restored'}).waitFor();assert.equal(await first.locator('.recorded-choice').textContent(),'Recorded: Reject');
    assert.equal(await page.evaluate(()=>localStorage.length),0);
    const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(axe.violations.map(v=>v.id),[]);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:`${output}/review-${width}.png`,fullPage:true});
    await page.locator('#brief').fill(input.brief+'\nChanged question.');
    assert(await page.getByRole('button',{name:'Download review',exact:true}).isDisabled());assert(await first.locator('select').isDisabled());
    assert.deepEqual(errors,[]);
    reports.push({width,sample_import:true,cross_category:true,explicit_choice:true,required_reason:true,draft_navigation:true,undo:true,source_readback:true,json_and_markdown_exports:true,stale_proposal_rejected:true,false_quote_rejected:true,restore_after_reload:true,changed_input_blocks_export:true,no_persistence:true,axe_violations:0,overflow:false,page_errors:errors});
    await context.close();
  }
  await fs.writeFile(`${output}/report.json`,JSON.stringify({scope:'Fictional developer tasks, not user effectiveness',reports},null,2));console.log(JSON.stringify({output,reports}));
}finally{await browser?.close();if(server.exitCode===null){server.kill();await once(server,'exit');}}
